name: memora_application
description: "A new Flutter project."# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Please adjust to your Flutter SDK version if different

dependencies:
  flutter:
    sdk: flutter

  # --- Firebase Services ---
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4

  # --- Backend Communication ---
  http: ^1.2.1

  # --- Local Storage ---
  shared_preferences: ^2.2.2


  # --- UI & Utilities ---
  cupertino_icons: ^1.0.6
  permission_handler: ^12.0.1
  
  # --- NEW: For showing standard local notifications ---
  flutter_local_notifications: ^17.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    # - assets/other_images/
